name: Deploy via Github-Locaweb via ftp

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Fetch remote changes
        run: |
          git fetch
    
      - name: Copy changed files
        run: |
          mkdir -p changed_files
          if [ -n "${{ steps.files.outputs.changed_files }}" ]; then
            echo "${{ steps.files.outputs.changed_files }}" | xargs -I {} sh -c 'mkdir -p changed_files/$(dirname {}) && cp {} changed_files/{}'
          fi
           
      - name: Deploy changed files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          local-dir: changed_files/