name: Deploy via ftp

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get Changed Files
      id: get_changed_files
      run: |
        echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localDir: "${{ steps.get_changed_files.outputs.files }}"



# name: Deploy via ftp

# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

# jobs:
#   deploy:
#     name: Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v3

#     - name: FTP Deploy Locaweb
#       uses: locaweb/ftp-deploy@1.0.0
#       with:
#         host: ${{ secrets.HOST }}
#         user: ${{ secrets.USER }}
#         password: ${{ secrets.PASS }}
#         localDir: "."   

            
        
        # Adicione mais passos conforme necessário para configurações específicas do seu projeto.
        
