name: Deploy via Github-Locaweb via ftp

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
    
      - name: Fetch remote changes
        run: |
          git fetch
    
      - name: Get changed files
        run: |
          git diff --name-only HEAD HEAD~1
          changed_files=$(echo "${GITHUB_FILES}" | tr '\n' ' ')
    
      - name: Copy changed files
        run: |
          mkdir changed_files
          cp $(echo "${changed_files}") changed_files
    
      - name: Deploy changed files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp://${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          local-dir: changed_files