name: Deploy via Github-Locaweb via ftp

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
    
      - name: Fetch remote changes
        run: |
          git fetch
    
      - name: Check changed files
        id: files
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]
            then
              echo "::set-output name=changed_files::$(git diff --name-only HEAD HEAD~1)"
          fi
      - name: Copy changed files
        run: |
          if [ -n "${{ steps.files.outputs.changed_files }}" ]; then
            mkdir changed_files
            echo "${{ steps.files.outputs.changed_files }}" | xargs -I {} cp --parents {} changed_files/
          fi
      - name: Deploy changed files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp://${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          local-dir: changed_files/