name: Deploy via Github-Locaweb via ftp

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Fetch remote changes
        run: |
          git fetch
    
      - name: Check changed files
        id: files
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]
          then
            echo "::set-output name=changed_files::$(git diff --name-only HEAD HEAD~1)"
          fi
           
      - name: Check changed files
        id: files
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]
          then
            echo "::set-output name=changed_files::$(git diff --name-only HEAD HEAD~1)"
          fi
      - name: Deploy changed files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          local-dir: changed_files/