name: Deploy via Github-Locaweb via ftp

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
    
      - name: Fetch remote changes
        run: |
          git fetch
    
      - name: Check changed files
        run: |
            if [ $(git rev-list --count HEAD) -gt 1 ]
            then
              git diff --name-only HEAD HEAD~1
              changed_files=$(echo "${GITHUB_FILES}" | tr '\n' ' ')
            fi
    
      - name: Copy changed files
        run: |
          if [ -n "${changed_files}" ]; then
            mkdir changed_files
            cp ${changed_files} changed_files/
          fi
    
      - name: Deploy changed files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp://${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          local-dir: changed_files